# Generated by Django 4.2.13 on 2024-06-29 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=datetime.datetime(2024, 6, 29, 10, 30, 37, 49351, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
