# Generated by Django 4.2.13 on 2024-06-30 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 6, 30, 6, 48, 6, 303451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
